lsst/ctrl_bps_parsl

python/lsst/ctrl/bps/parsl/job.py
When using the execution butler, this needs to be set to the location of the job-specific copy.
=> Set the butlerConfig field in the pipetask command line

etc/execution_butler_copy_files.yaml
The --datastore-root option was renamed --target-datastore-root
during review, but this file was not updated.
=> fix bitrot in execution_butler_copy_files.yaml

doc/changes/DM-37215.misc.rst, pyproject.toml, tests/test_config.py, tests/test_import.py
Tests (including flake8) are importing parsl, which isn't in base LSST env, so temporarily disabling them.
=> DM-37215: disable tests

doc/changes/DM-32764.feature.rst, doc/lsst.ctrl.bps.parsl/use.rst, python/lsst/ctrl/bps/parsl/sites/slurm.py
This saves users from having to subclass the Slurm site.
=> Slurm: add support for getting scheduler_options from BPS config

mypy.ini, python/lsst/ctrl/bps/parsl/sites/princeton.py
=> DM-38146: Update Princeton site interface from ib0 to op0

doc/changes/DM-38184.feature.md, doc/lsst.ctrl.bps.parsl/use.rst, python/lsst/ctrl/bps/parsl/sites/princeton.py
=> DM-38184: Increase parsl wait time for Princeton site

doc/changes/DM-39885.bugfix.rst, python/lsst/ctrl/bps/parsl/job.py
=> DM-39885: Fully substitute symbolic environment variables in symbolic filenames

.github/workflows/do_not_merge.yaml, .github/workflows/lint.yaml, .github/workflows/rebase_checker.yaml, .gitignore, doc/changes/DM-37215.misc.rst, tests/test_config.py, tests/test_import.py
=> DM-38499: Fix minor ruff issue and re-enable tests

doc/changes/DM-41229.feature.rst, doc/lsst.ctrl.bps.parsl/use.rst, python/lsst/ctrl/bps/parsl/job.py, tests/test_job.py
=> DM-41229: Distribute log files across subdirs.

python/lsst/ctrl/bps/parsl/sites/princeton.py, requirements.txt
=> DM-42421: Remove --slurmd-debug argument from Princeton site

.github/workflows/build_docs.yaml, requirements.txt
=> DM-42425: Remove temporary requirements in ctrl_bps_parsl

.pre-commit-config.yaml, doc/changes/DM-41229.feature.rst, doc/lsst.ctrl.bps.parsl/index.rst, doc/lsst.ctrl.bps.parsl/use.rst, python/lsst/ctrl/bps/parsl/configuration.py, python/lsst/ctrl/bps/parsl/site.py, python/lsst/ctrl/bps/parsl/sites/ccin2p3.py, python/lsst/ctrl/bps/parsl/workflow.py, setup.cfg
=> DM-42631: Add CC-IN2P3 (Slurm) as a target site

doc/changes/DM-44110.misc.rst, tests/test_job.py
Updated selected unit tests so they reflect the changes in `BpsConfig.__init__()` behavior.
=> DM-44110-hotfix: Add ability for WMS-specific default configs

doc/changes/DM-45863.bugfix.md, python/lsst/ctrl/bps/parsl/job.py
=> DM-45863: Resolve BPS parsl AttributeError for attr 'keys'

doc/lsst.ctrl.bps.parsl/use.rst, python/lsst/ctrl/bps/parsl/sites/ccin2p3.py
=> DM-46082: Honor job requirements specified in BPS config file

doc/changes/DM-47399.bugfix.md, pyproject.toml, python/lsst/ctrl/bps/parsl/sites/ccin2p3.py, python/lsst/ctrl/bps/parsl/sites/local.py, requirements.txt
Fixed an error caused by the deprecated `max_workers` parameter, which was removed in Parsl version 2024.09.09 following its deprecation in version 2024.03.04.
=> DM-47399: max_workers is deprecated for max_workers_per_node

doc/changes/DM-44110.misc.rst, doc/changes/DM-45863.bugfix.md, doc/changes/DM-47399.bugfix.md, doc/lsst.ctrl.bps.parsl/CHANGES.rst, requirements.txt
=> DM-47673: v28 release notes

.github/workflows/build.yaml, .pre-commit-config.yaml, doc/changes/DM-44110.misc.rst, doc/changes/DM-45863.bugfix.md, doc/changes/DM-47399.bugfix.md, doc/lsst.ctrl.bps.parsl/CHANGES.rst
=> DM-47673: v28 release notes (cherry-picked)

.gitignore, python/lsst/ctrl/bps/parsl/sites/ccin2p3.py
=> DM-48321: Ignore dist-info directory

doc/changes/dm-48539.feature.rst, doc/lsst.ctrl.bps.parsl/CHANGES.rst, requirements.txt
=> DM-49674 (v29): v29 release notes
